FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      software-properties-common \
      gnupg2 \
      ca-certificates && \
    add-apt-repository ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      curl \
      unzip \
      php7.4-cli \
      php7.4-fpm \
      php7.4-ctype \
      php7.4-iconv \
      php7.4-json \
      php7.4-mbstring \
      php7.4-opcache \
      php7.4-xml \
      php7.4-curl \
      php7.4-zip \
      php7.4-intl \
      php7.4-pgsql \
      postgresql-client \
      fish && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN chmod 0755 /usr/local/bin/composer

RUN usermod -u 10033 www-data && \
    groupmod -g 10033 www-data && \
    mkdir -p /var/www /run/php && \
    chown -R www-data:www-data /var/www && \
    chmod 777 /run/php

COPY .ops/docker/php/php-fpm.conf /etc/php/7.4/fpm/php-fpm.conf
COPY .ops/docker/php/www.conf /etc/php/7.4/fpm/pool.d/www.conf

WORKDIR /var/www

COPY .ops/docker/php/entrypoint-dev.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 9000 8080

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm7.4", "-F"]
